config/routes.rb
Friendap::Application.routes.draw do

  resources :invitation_sents

  match '/api/testuser' => 'api#testuser'
  match '/api/login' => 'api#login'
  match '/api/current_user_prayers' => 'api#current_user_prayers'
  match '/api/selected_user_prayers' => 'api#selected_user_prayers'
  match '/api/prayers' => 'api#prayers'
  match '/api/create_prayer' => 'api#create_prayer'
  match '/api/get_friend_list' => 'api#get_friend_list'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/delete_prayer' => 'api#delete_prayer'
  match '/api/create_user' => 'api#create_user'
  match '/api/friend_request' => 'api#friend_request'
  match '/api/rejected_friends' => 'api#rejected_friends'
  match '/api/get_invitation_pending' => 'api#get_invitation_pending'
  match '/api/accept_invitation' => 'api#accept_invitation'
  match '/api/reject_invitation' => 'api#reject_invitation'
  match '/api/get_prayer_comments' => 'api#get_prayer_comments'
  match '/api/add_prayer_viewed' => 'api#add_prayer_viewed'
  match '/api/add_prayer_prayed' => 'api#add_prayer_prayed'
  match '/api/add_comment' => 'api#add_comment'
  match '/api/logout' => 'api#logout'
  match '/api/get_current_user_profile' => 'api#get_current_user_profile'
  match '/api/change_password' => 'api#change_password'
  
  match '/users/edit_image' => 'users#edit_image'
  match '/users/update_image' => 'users#update_image'
  match '/users/change_password' => 'users#change_password'
  resources :api
  resources :prayers
  resources :comments
  match '/homes' => 'users#user_action'
  resources :reject_friends
  resources :homes
  resources :facebooktests
  match '/join_the_network/:id' => 'friend_requests#join_the_network'
  match '/users/code_image/:id' => 'users#code_image'
  match '/users/show_profile/:id' => 'users#show_profile'
  match '/reset/:reset_code' => 'users#reset'
  match '/users/forgot' => 'users#forgot'
  match '/users/update_password' => 'users#update_password'
  match '/users/edit_profile' => 'users#edit_profile'
  match '/users/update_profile' => 'users#update_profile'
  match '/users/koalatest' => 'users#koalatest'
  match '/friend_requests/friend_request' => 'friend_requests#friend_request'
  match '/friend_requests/send_friend_request' => 'friend_requests#send_friend_request'
  resources :friend_requests
  match '/friendships/invite_friend' => 'friendships#invite_friend'
  match '/friendships/pending_invitation' => 'friendships#pending_invitation'
  match '/friendships/accept_invitation' => 'friendships#accept_invitation'
  match '/friendships/reject_invitation' => 'friendships#reject_invitation'
  match '/friendships/invitation_by' => 'friendships#invitation_by'
  match '/friendships/invite' => 'friendships#invite'
  match '/friendships/invitation' => 'friendships#invitation'
  match '/friendships/get_all_friend' => 'friendships#get_all_friend'
  match '/users/my_profile' => 'users#my_profile'
  resources :friendships
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match "/post_on_wall" => "users#post_on_wall"
  root :to => "users#user_action"

end

app/models/invitation_sent.rb
class InvitationSent < ActiveRecord::Base
end

app/controllers/invitation_sents_controller.rb
class InvitationSentsController < ApplicationController
  # GET /invitation_sents
  # GET /invitation_sents.xml
  def index
    @invitation_sents = InvitationSent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invitation_sents }
    end
  end

  # GET /invitation_sents/1
  # GET /invitation_sents/1.xml
  def show
    @invitation_sent = InvitationSent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invitation_sent }
    end
  end

  # GET /invitation_sents/new
  # GET /invitation_sents/new.xml
  def new
    @invitation_sent = InvitationSent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invitation_sent }
    end
  end

  # GET /invitation_sents/1/edit
  def edit
    @invitation_sent = InvitationSent.find(params[:id])
  end

  # POST /invitation_sents
  # POST /invitation_sents.xml
  def create
    @invitation_sent = InvitationSent.new(params[:invitation_sent])

    respond_to do |format|
      if @invitation_sent.save
        format.html { redirect_to(@invitation_sent, :notice => 'Invitation sent was successfully created.') }
        format.xml  { render :xml => @invitation_sent, :status => :created, :location => @invitation_sent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invitation_sent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invitation_sents/1
  # PUT /invitation_sents/1.xml
  def update
    @invitation_sent = InvitationSent.find(params[:id])

    respond_to do |format|
      if @invitation_sent.update_attributes(params[:invitation_sent])
        format.html { redirect_to(@invitation_sent, :notice => 'Invitation sent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invitation_sent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invitation_sents/1
  # DELETE /invitation_sents/1.xml
  def destroy
    @invitation_sent = InvitationSent.find(params[:id])
    @invitation_sent.destroy

    respond_to do |format|
      format.html { redirect_to(invitation_sents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/invitation_sents_helper.rb
module InvitationSentsHelper
end

app/views/invitation_sents/_form.html.erb
<%= form_for(@invitation_sent) do |f| %>
  <% if @invitation_sent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation_sent.errors.count, "error") %> prohibited this invitation_sent from being saved:</h2>

      <ul>
      <% @invitation_sent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitation_sents/edit.html.erb
<h1>Editing invitation_sent</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation_sent %> |
<%= link_to 'Back', invitation_sents_path %>

app/views/invitation_sents/index.html.erb
<h1>Listing invitation_sents</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitation_sents.each do |invitation_sent| %>
  <tr>
    <td><%= link_to 'Show', invitation_sent %></td>
    <td><%= link_to 'Edit', edit_invitation_sent_path(invitation_sent) %></td>
    <td><%= link_to 'Destroy', invitation_sent, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation sent', new_invitation_sent_path %>

app/views/invitation_sents/new.html.erb
<h1>New invitation_sent</h1>

<%= render 'form' %>

<%= link_to 'Back', invitation_sents_path %>

app/views/invitation_sents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_invitation_sent_path(@invitation_sent) %> |
<%= link_to 'Back', invitation_sents_path %>