config/routes.rb
Friendap::Application.routes.draw do

  resources :invitation_sents

  match '/api/testuser' => 'api#testuser'
  match '/api/login' => 'api#login'
  match '/api/current_user_prayers' => 'api#current_user_prayers'
  match '/api/selected_user_prayers' => 'api#selected_user_prayers'
  match '/api/prayers' => 'api#prayers'
  match '/api/create_prayer' => 'api#create_prayer'
  match '/api/get_friend_list' => 'api#get_friend_list'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/delete_prayer' => 'api#delete_prayer'
  match '/api/create_user' => 'api#create_user'
  match '/api/friend_request' => 'api#friend_request'
  match '/api/rejected_friends' => 'api#rejected_friends'
  match '/api/get_invitation_pending' => 'api#get_invitation_pending'
  match '/api/accept_invitation' => 'api#accept_invitation'
  match '/api/reject_invitation' => 'api#reject_invitation'
  match '/api/get_prayer_comments' => 'api#get_prayer_comments'
  match '/api/add_prayer_viewed' => 'api#add_prayer_viewed'
  match '/api/add_prayer_prayed' => 'api#add_prayer_prayed'
  match '/api/add_comment' => 'api#add_comment'
  match '/api/logout' => 'api#logout'
  match '/api/get_current_user_profile' => 'api#get_current_user_profile'
  match '/api/change_password' => 'api#change_password'
  
  match '/users/edit_image' => 'users#edit_image'
  match '/users/update_image' => 'users#update_image'
  match '/users/change_password' => 'users#change_password'
  resources :api
  resources :prayers
  resources :comments
  match '/homes' => 'users#user_action'
  resources :reject_friends
  resources :homes
  resources :facebooktests
  match '/join_the_network/:id' => 'friend_requests#join_the_network'
  match '/users/code_image/:id' => 'users#code_image'
  match '/users/show_profile/:id' => 'users#show_profile'
  match '/reset/:reset_code' => 'users#reset'
  match '/users/forgot' => 'users#forgot'
  match '/users/update_password' => 'users#update_password'
  match '/users/edit_profile' => 'users#edit_profile'
  match '/users/update_profile' => 'users#update_profile'
  match '/users/koalatest' => 'users#koalatest'
  match '/friend_requests/friend_request' => 'friend_requests#friend_request'
  match '/friend_requests/send_friend_request' => 'friend_requests#send_friend_request'
  resources :friend_requests
  match '/friendships/invite_friend' => 'friendships#invite_friend'
  match '/friendships/pending_invitation' => 'friendships#pending_invitation'
  match '/friendships/accept_invitation' => 'friendships#accept_invitation'
  match '/friendships/reject_invitation' => 'friendships#reject_invitation'
  match '/friendships/invitation_by' => 'friendships#invitation_by'
  match '/friendships/invite' => 'friendships#invite'
  match '/friendships/invitation' => 'friendships#invitation'
  match '/friendships/get_all_friend' => 'friendships#get_all_friend'
  match '/users/my_profile' => 'users#my_profile'
  resources :friendships
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match "/post_on_wall" => "users#post_on_wall"
  root :to => "users#user_action"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
   include Amistad::FriendshipModel
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    
  before_filter :check_login
  layout "login"
  def check_login
      if logged_in?
      else   
         redirect_to "/login"
      end   
  end    
    
  def invite
  end  


  def invite_friend
     @user = User.find_by_login(params[:username])
     @friend = User.find_by_login(params[:friendname]) 
     @user.invite  @friend
     render :text=>"#{@user.login} invited #{@friend.login}"
  end  

  def pending_invitation
    @user = User.find(current_user.id)       
    @pending_invited_by = @user.pending_invited_by
    @rejected_friends = @user.rejected
    @rejected_friends_req = @user.find_friend_ship_rejected
  end  
    
  #the friends who invited user and user accepts it
  def invitation_by
    @user = User.find(3)       
    @invitedby = @user.invited_by
  end  
  #the friend to whom user invites
  def  invitation
     @user = User.find(3)       
     @invitedfrom = @user.invited
  end  

  def accept_invitation
    @user = User.find(current_user.id)       
    @friend = User.find(params[:id])  
    @user.approve  @friend
    flash[:notice] = "Friendship is accepted"
    redirect_to :back
  end  
    
   def reject_invitation
    @user = User.find(current_user.id)       
    @friend = User.find(params[:id])  
    @user.reject  @friend
    flash[:notice] = "Friendship is rejected"
    redirect_to :back

          
   end  


  def get_all_friend
      @user = User.find(current_user.id)       
      @userallfriend = @user.friends
  end  
 


  # GET /friendships
  # GET /friendships.xml
  def index
    @friendships = Friendship.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.xml
  def show
    @friendship = Friendship.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.xml
  def new
    @friendship = Friendship.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.xml
  def create
    @friendship = Friendship.new(params[:friendship])
    respond_to do |format|
      if @friendship.save
        format.html { redirect_to(@friendship, :notice => 'Friendship was successfully created.') }
        format.xml  { render :xml => @friendship, :status => :created, :location => @friendship }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friendship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.xml
  def update
    @friendship = Friendship.find(params[:id])
    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to(@friendship, :notice => 'Friendship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @friendship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.xml
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to(friendships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/get_all_friend.html.erb
    <div id="middle_div"> 
      <p style="padding-left:20%;padding-top:2%">  <label class="prayer_label">Following Are The Friends Of <%=current_user.login%></label></p>
       <div id="friend_list">
            Friend List
            <%for getallfriend in @userallfriend %>
                           <br/>
                        <p class="fcomment" style="padding-top:25px;"> 
                                   <div >
                                       <%if getallfriend.binary_data.blank?%>   
                                          <img src="/images/blank.jpeg"></img>
                                        <%else%>
            <%= image_tag "/users/code_image/#{getallfriend.id}",:size=>"50x50",:style=>"float:left;padding:5px;" %>
       
                                                  
                                        <%end%>  

                                   <a href="/users/show_profile/<%=getallfriend.id%>"><%=getallfriend.login%></a>
                                    </div>
                         </p>
               
               
          <%end%>  
      
       </div>
       
    </div>
    

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/invitation.html.erb
Following are the friends to whome user invited

<br/><br/><br/>
<% for invitationfrom in @invitedfrom%>
   <%=invitationfrom.login%>
   <br/>
<%end%>

app/views/friendships/invitation_by.html.erb
Following Are The friends who invited the user
<br/><br/><br/>
<p>
<%for invitedby in @invitedby %>
    <%=invitedby.login%>
    <br/>
<%end%>
</p>

app/views/friendships/invite.html.erb
<h1>New friendship</h1>









<h1>Enter Friend Name Who Invites Another Friend</h1>

  
  <%=  form_tag ('/friendships/invite_friend') do %>
     <p><%= label_tag 'Self Name' %><br/>
     <%= text_field_tag :username %></p>
     <p><%= label_tag 'Friend Name' %><br/>
     <%= text_field_tag :friendname %></p>

    <div><%= submit_tag 'Invite' %></div>
  <% end %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/pending_invitation.html.erb
    <div id="middle_div"> 
      <p style="padding-left:20%;padding-top:2%">  <label class="prayer_label">Following Are The Invitation Pending For <%=current_user.login%></label></p>
       <div id="friend_list">
           <span class="prayer_label" style="font-weight:normal"> Click On User Name To Accept The Invitation</span>
                   <% for pending_invited in @pending_invited_by%>  
                          
 <div style="padding-top:50px">
                                       <%if pending_invited.binary_data.blank?%>   
                                          <img src="/images/blank.jpeg"></img>
                                        <%else%>
        <%= image_tag "/users/code_image/#{pending_invited.id}",:size=>"50x50",:style=>"float:left;padding:5px;" %>
                     
                                        <%end%>  
<span class="prayer_label">
                                 Accept:-<%= link_to pending_invited.login ,  :controller=>'friendships' ,:action=>'accept_invitation',:id=>pending_invited.id%>
                                 Reject:-<%= link_to pending_invited.login ,  :controller=>'friendships' ,:action=>'reject_invitation',:id=>pending_invited.id%>
                                
                                 
                                 </span>
                                    </div>
                        <%end%>  
  
    
       </div>
<div>       
</div>
  <div style="padding-left:120px;padding-top:30px;">
   <span class="prayer_label"> Rejected Friendships Request</span>
      <%for rejuser in @rejected_friends%>
        <br/>
        <%=rejuser.login%>
      <%end%>


      <%for rejuser in @rejected_friends_req%>
        <br/>
        <%=rejuser.user.login%>
      <%end%>

  </div>        
    
    
    
</div>
    

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>