config/routes.rb
Friendap::Application.routes.draw do

  resources :invitation_sents

  match '/api/testuser' => 'api#testuser'
  match '/api/login' => 'api#login'
  match '/api/current_user_prayers' => 'api#current_user_prayers'
  match '/api/selected_user_prayers' => 'api#selected_user_prayers'
  match '/api/prayers' => 'api#prayers'
  match '/api/create_prayer' => 'api#create_prayer'
  match '/api/get_friend_list' => 'api#get_friend_list'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/delete_prayer' => 'api#delete_prayer'
  match '/api/create_user' => 'api#create_user'
  match '/api/friend_request' => 'api#friend_request'
  match '/api/rejected_friends' => 'api#rejected_friends'
  match '/api/get_invitation_pending' => 'api#get_invitation_pending'
  match '/api/accept_invitation' => 'api#accept_invitation'
  match '/api/reject_invitation' => 'api#reject_invitation'
  match '/api/get_prayer_comments' => 'api#get_prayer_comments'
  match '/api/add_prayer_viewed' => 'api#add_prayer_viewed'
  match '/api/add_prayer_prayed' => 'api#add_prayer_prayed'
  match '/api/add_comment' => 'api#add_comment'
  match '/api/logout' => 'api#logout'
  match '/api/get_current_user_profile' => 'api#get_current_user_profile'
  match '/api/change_password' => 'api#change_password'
  
  match '/users/edit_image' => 'users#edit_image'
  match '/users/update_image' => 'users#update_image'
  match '/users/change_password' => 'users#change_password'
  resources :api
  resources :prayers
  resources :comments
  match '/homes' => 'users#user_action'
  resources :reject_friends
  resources :homes
  resources :facebooktests
  match '/join_the_network/:id' => 'friend_requests#join_the_network'
  match '/users/code_image/:id' => 'users#code_image'
  match '/users/show_profile/:id' => 'users#show_profile'
  match '/reset/:reset_code' => 'users#reset'
  match '/users/forgot' => 'users#forgot'
  match '/users/update_password' => 'users#update_password'
  match '/users/edit_profile' => 'users#edit_profile'
  match '/users/update_profile' => 'users#update_profile'
  match '/users/koalatest' => 'users#koalatest'
  match '/friend_requests/friend_request' => 'friend_requests#friend_request'
  match '/friend_requests/send_friend_request' => 'friend_requests#send_friend_request'
  resources :friend_requests
  match '/friendships/invite_friend' => 'friendships#invite_friend'
  match '/friendships/pending_invitation' => 'friendships#pending_invitation'
  match '/friendships/accept_invitation' => 'friendships#accept_invitation'
  match '/friendships/reject_invitation' => 'friendships#reject_invitation'
  match '/friendships/invitation_by' => 'friendships#invitation_by'
  match '/friendships/invite' => 'friendships#invite'
  match '/friendships/invitation' => 'friendships#invitation'
  match '/friendships/get_all_friend' => 'friendships#get_all_friend'
  match '/users/my_profile' => 'users#my_profile'
  resources :friendships
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match "/post_on_wall" => "users#post_on_wall"
  root :to => "users#user_action"

end

app/models/facebooktest.rb
class Facebooktest < ActiveRecord::Base
end

app/controllers/facebooktests_controller.rb
class FacebooktestsController < ApplicationController
  # GET /facebooktests
  # GET /facebooktests.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @facebooktests }
    end
  end

  # GET /facebooktests/1
  # GET /facebooktests/1.xml
  def show
    @facebooktest = Facebooktest.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @facebooktest }
    end
  end

  # GET /facebooktests/new
  # GET /facebooktests/new.xml
  def new
    @facebooktest = Facebooktest.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @facebooktest }
    end
  end

  # GET /facebooktests/1/edit
  def edit
    @facebooktest = Facebooktest.find(params[:id])
  end

  # POST /facebooktests
  # POST /facebooktests.xml
  def create
    @facebooktest = Facebooktest.new(params[:facebooktest])
    respond_to do |format|
      if @facebooktest.save
        format.html { redirect_to(@facebooktest, :notice => 'Facebooktest was successfully created.') }
        format.xml  { render :xml => @facebooktest, :status => :created, :location => @facebooktest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @facebooktest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /facebooktests/1
  # PUT /facebooktests/1.xml
  def update
    @facebooktest = Facebooktest.find(params[:id])
     respond_to do |format|
      if @facebooktest.update_attributes(params[:facebooktest])
        format.html { redirect_to(@facebooktest, :notice => 'Facebooktest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @facebooktest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /facebooktests/1
  # DELETE /facebooktests/1.xml
  def destroy
    @facebooktest = Facebooktest.find(params[:id])
    @facebooktest.destroy
     respond_to do |format|
      format.html { redirect_to(facebooktests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/facebooktests_helper.rb
module FacebooktestsHelper
end

app/views/facebooktests/_form.html.erb
<%= form_for(@facebooktest) do |f| %>
  <% if @facebooktest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facebooktest.errors.count, "error") %> prohibited this facebooktest from being saved:</h2>

      <ul>
      <% @facebooktest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facebooktests/edit.html.erb
<h1>Editing facebooktest</h1>

<%= render 'form' %>

<%= link_to 'Show', @facebooktest %> |
<%= link_to 'Back', facebooktests_path %>

app/views/facebooktests/index.html.erb
< id="fb-root">< /div>
< src="http://connect.facebook.net/en_US/all.js">
<script>
FB.init({
appId : '141640805875847',
status : true, // check login status
cookie : true, // enable cookies to allow the server to access the session
xfbml : true // parse XFBML
});

FB.Event.subscribe('auth.sessionChange', function(response) {
if (response.session) {
location.href = '/user/account';
// A user has logged in, and a new cookie has been saved
} else {
location.href = '/user/login';
// The user has logged out, and the cookie has been cleared
}
});
< /script>
< perms="email,user_birthday">< /fb:login-button>

app/views/facebooktests/new.html.erb
<h1>New facebooktest</h1>

<%= render 'form' %>

<%= link_to 'Back', facebooktests_path %>

app/views/facebooktests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_facebooktest_path(@facebooktest) %> |
<%= link_to 'Back', facebooktests_path %>