config/routes.rb
Friendap::Application.routes.draw do

  resources :invitation_sents

  match '/api/testuser' => 'api#testuser'
  match '/api/login' => 'api#login'
  match '/api/current_user_prayers' => 'api#current_user_prayers'
  match '/api/selected_user_prayers' => 'api#selected_user_prayers'
  match '/api/prayers' => 'api#prayers'
  match '/api/create_prayer' => 'api#create_prayer'
  match '/api/get_friend_list' => 'api#get_friend_list'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/get_all_users' => 'api#get_all_users'
  match '/api/delete_prayer' => 'api#delete_prayer'
  match '/api/create_user' => 'api#create_user'
  match '/api/friend_request' => 'api#friend_request'
  match '/api/rejected_friends' => 'api#rejected_friends'
  match '/api/get_invitation_pending' => 'api#get_invitation_pending'
  match '/api/accept_invitation' => 'api#accept_invitation'
  match '/api/reject_invitation' => 'api#reject_invitation'
  match '/api/get_prayer_comments' => 'api#get_prayer_comments'
  match '/api/add_prayer_viewed' => 'api#add_prayer_viewed'
  match '/api/add_prayer_prayed' => 'api#add_prayer_prayed'
  match '/api/add_comment' => 'api#add_comment'
  match '/api/logout' => 'api#logout'
  match '/api/get_current_user_profile' => 'api#get_current_user_profile'
  match '/api/change_password' => 'api#change_password'
  
  match '/users/edit_image' => 'users#edit_image'
  match '/users/update_image' => 'users#update_image'
  match '/users/change_password' => 'users#change_password'
  resources :api
  resources :prayers
  resources :comments
  match '/homes' => 'users#user_action'
  resources :reject_friends
  resources :homes
  resources :facebooktests
  match '/join_the_network/:id' => 'friend_requests#join_the_network'
  match '/users/code_image/:id' => 'users#code_image'
  match '/users/show_profile/:id' => 'users#show_profile'
  match '/reset/:reset_code' => 'users#reset'
  match '/users/forgot' => 'users#forgot'
  match '/users/update_password' => 'users#update_password'
  match '/users/edit_profile' => 'users#edit_profile'
  match '/users/update_profile' => 'users#update_profile'
  match '/users/koalatest' => 'users#koalatest'
  match '/friend_requests/friend_request' => 'friend_requests#friend_request'
  match '/friend_requests/send_friend_request' => 'friend_requests#send_friend_request'
  resources :friend_requests
  match '/friendships/invite_friend' => 'friendships#invite_friend'
  match '/friendships/pending_invitation' => 'friendships#pending_invitation'
  match '/friendships/accept_invitation' => 'friendships#accept_invitation'
  match '/friendships/reject_invitation' => 'friendships#reject_invitation'
  match '/friendships/invitation_by' => 'friendships#invitation_by'
  match '/friendships/invite' => 'friendships#invite'
  match '/friendships/invitation' => 'friendships#invitation'
  match '/friendships/get_all_friend' => 'friendships#get_all_friend'
  match '/users/my_profile' => 'users#my_profile'
  resources :friendships
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match "/post_on_wall" => "users#post_on_wall"
  root :to => "users#user_action"

end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_filter :check_the_login ,:except=>:join_the_network
  layout "login"

  def check_the_login
      if logged_in?
      else 
        flash[:notice] = "Please Login To Send Email"
        redirect_to "/login"
      end  
  end  

  def join_the_network
      session[:friendid] = params[:id]
      flash[:notice] = "Please Register To Accept The Invitation"
      redirect_to "/users/new"
  end  

  def friend_request
      friend = User.find_by_email(params[:useremail])
      invitation_sent = InvitationSent.where(["from_email = ? and to_email = ?",current_user.email,params[:useremail]])
      if  invitation_sent.blank?
             invsnt=InvitationSent.new(:from_email=>current_user.email,:to_email=>params[:useremail])
             invsnt.save
              if friend.blank?
                begin
                  Notifier.friend_request(params[:useremail],current_user,request.host_with_port).deliver       
                rescue  
                end  
              else  
                  current_user.invite  friend
              end
              flash[:notice] = "Your Invitation Has Been Sent"
              redirect_to "/"
      else  
               flash[:notice] = "You Already Sent The Invitation"
               redirect_to "/"
      end              
  end  
  
  

  # GET /friend_requests
  # GET /friend_requests.xml
  def index
    @friend_requests = FriendRequest.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friend_requests }
    end
  end

  # GET /friend_requests/1
  # GET /friend_requests/1.xml
  def show
    @friend_request = FriendRequest.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @friend_request }
    end
  end

  # GET /friend_requests/new
  # GET /friend_requests/new.xml
  def new
    @friend_request = FriendRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @friend_request }
    end
  end

  # GET /friend_requests/1/edit
  def edit
    @friend_request = FriendRequest.find(params[:id])
  end

  # POST /friend_requests
  # POST /friend_requests.xml
  def create
    @friend_request = FriendRequest.new(params[:friend_request])
    respond_to do |format|
      if @friend_request.save
        format.html { redirect_to(@friend_request, :notice => 'Friend request was successfully created.') }
        format.xml  { render :xml => @friend_request, :status => :created, :location => @friend_request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friend_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friend_requests/1
  # PUT /friend_requests/1.xml
  def update
    @friend_request = FriendRequest.find(params[:id])
    respond_to do |format|
      if @friend_request.update_attributes(params[:friend_request])
        format.html { redirect_to(@friend_request, :notice => 'Friend request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @friend_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_requests/1
  # DELETE /friend_requests/1.xml
  def destroy
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.destroy
    respond_to do |format|
      format.html { redirect_to(friend_requests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<%= form_for(@friend_request) do |f| %>
  <% if @friend_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
      <% @friend_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friend_requests/edit.html.erb
<h1>Editing friend_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend_request %> |
<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/index.html.erb
<h1>Listing friend_requests</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friend_requests.each do |friend_request| %>
  <tr>
    <td><%= link_to 'Show', friend_request %></td>
    <td><%= link_to 'Edit', edit_friend_request_path(friend_request) %></td>
    <td><%= link_to 'Destroy', friend_request, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend request', new_friend_request_path %>

app/views/friend_requests/new.html.erb
<h1>New friend_request</h1>

<%= render 'form' %>

<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/send_friend_request.html.erb
  <div id="middle_div"> 
               <div id="form_divemail"> 
     <%=  form_tag ('/friend_requests/friend_request') do %>
       <label for="name" class="form_label">Enter Email Id For Friend</label>
        <br/>
        <%= text_field_tag :useremail,"",:class=>"form_input" %>
        <br/>

<button id="contactsubmit" type="submit">Submit</button>
<% end %>


     </div>
              
              
    </div>

app/views/friend_requests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friend_request_path(@friend_request) %> |
<%= link_to 'Back', friend_requests_path %>